export const TabNav = {
  Home: 'Home',
  Profile: 'Profile',
  Discover: 'Discover',
  Following: 'Following',
  Notification: 'Notification',
};

export const StackNav = {
  Auth: 'Auth',
  TabBar: 'TabBar',
  Splash: 'Splash',
  Register: 'Register',
  onBoarding: 'onBoarding',
  SelectInterest: 'SelectInterest',
  SetPin: 'SetPin',
  SetUpProfile: 'SetUpProfile',
  Privacy: 'Privacy',
  PrivacyPolicy: 'PrivacyPolicy',
  HelpCenter: 'HelpCenter',
  Security: 'Security',
  Language: 'Language',
  Birthday: 'Birthday',
  Gender: 'Gender',
  Setting: 'Setting',
  EditProfile: 'EditProfile',
  Report: 'Report',
  ProfileDetail: 'ProfileDetail',
  ManageAccount: 'ManageAccount',
  TrendingSound: 'TrendingSound',
  Search: 'Search',
  SearchTop: 'SearchTop',
  SearchVideo: 'SearchVideo',
  SearchSound: 'SearchSound',
  SearchUser: 'SearchUser',
  SearchLive: 'SearchLive',
  SearchHashtag: 'SearchHashtag',
  ReelsComponent: 'ReelsComponent',
  SelectLanguage: 'SelectLanguage',
  FeedBack: 'FeedBack',
  UpdateProfile: 'UpdateProfile',
  ParticularReelComponent: 'ParticularReelComponent',
};
